-- ============================================================
-- Migration : V1__create_users_table.sql
-- Purpose   : Creates the users table that stores registered
--             application users. Passwords are stored as BCrypt
--             hashes (strength 12) — never plaintext.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    -- Primary key — generated by the application layer
    id          BIGSERIAL       PRIMARY KEY,

    -- User's display name
    name        VARCHAR(55)    NOT NULL,

    -- Login identifier — must be globally unique
    email       VARCHAR(55)    NOT NULL,

    -- BCrypt-hashed password (strength 12); never stored in plain text
    password    VARCHAR(255)    NOT NULL,

    -- Audit columns present on every table
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Soft-delete flag; queries must always filter WHERE is_deleted = false
    is_deleted  BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Unique constraint on email to prevent duplicate accounts
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ============================================================
-- Rollback script (run manually if migration must be reverted)
-- DROP TABLE IF EXISTS users;
-- ============================================================
